matrix:
  include:
    - os: linux  
      sudo: required
      services: docker
      env: PLATFORM=linux

    - os: osx
      osx_image: xcode9.3

branches:
  except:
    - /^v[0-9]/
    
script:
  - if [[ $TRAVIS_PULL_REQUEST == "true" ]] || [[ $TRAVIS_BRANCH != "master" ]]; then bash ./ci_scripts/swiftlint.sh; fi
  - if [[ $TRAVIS_PULL_REQUEST == "true" ]] || [[ $TRAVIS_BRANCH != "master" ]]; then bash ./ci_scripts/test_on_ci.sh; fi
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then bash ./ci_scripts/tag_build.sh; fi


# Deployment to Github via Releases using person oauth token
before_deploy:
  - ./ci_scripts/build_on_ci.sh

deploy:
  - provider: releases
    api_key:
      secure: "gmCjp8g7PYQrHMyp2ACCBg2JJc+OpXoLfOJwqwKPXv5o5uHi+nh7ZH8oq/zFfKjCLs0c9K/fa4ADaagOSbBnFfdw6aH+3J0FTRp/+k37tvXPdeMc6eEcRT13CqEYqV9icqRx3JM7hpKx7waNLN1uHeDgEJW+wHJuKCAz1Z3xVnE7uWoFrCLwA5LfpKAnEX8qHY7wJrEEIuNcmFfPzZHEJdX2AMyHTFHN/sq5CDtRGsnPlsVJehAtwUTkmt/kARkxSdBMlBNXuJMLDTNH1XABRgu7y1t7sS+VYGCYGb5kb5bPQHsuD7fWBOWy2FbuoWecXATBiYOEzQZZ/Rk/gauc9GFvlV3rcYm6C8RIjrLF8dTCLoGXVa1c4jmo5oPf9L47ZjhJozJdG0WFOXBZUMQ3/q6sXMwP8PxjOTs01JHYfgRGUtJ5V8BUKZz5039p+KCIU06eYm8oRnFcpQ468Wf3Opn+yxHizUqI+YEFqizS0k/y2t2Qbon4XhuaxqXedFDaFBNf7bGIcMkrViZk99lLaYGsNZGhhNeu1xreCA2lLy2+FvO1Pc33I9dd40eWUoJT+eoQBrqPL1mLQjU7pVfIjU7pTTHJBBZNQhtsyU1VgKE6yknzbiorNOwZtVIC7n8aeijSwns9tnRR1y14y5vEY8kOl5jL8KeluyWUdoCCOos=" 
    file_glob: true
    file: linux-release/bitriseTrigger_linux
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = "linux"

  - provider: releases
    api_key:
      secure: "gmCjp8g7PYQrHMyp2ACCBg2JJc+OpXoLfOJwqwKPXv5o5uHi+nh7ZH8oq/zFfKjCLs0c9K/fa4ADaagOSbBnFfdw6aH+3J0FTRp/+k37tvXPdeMc6eEcRT13CqEYqV9icqRx3JM7hpKx7waNLN1uHeDgEJW+wHJuKCAz1Z3xVnE7uWoFrCLwA5LfpKAnEX8qHY7wJrEEIuNcmFfPzZHEJdX2AMyHTFHN/sq5CDtRGsnPlsVJehAtwUTkmt/kARkxSdBMlBNXuJMLDTNH1XABRgu7y1t7sS+VYGCYGb5kb5bPQHsuD7fWBOWy2FbuoWecXATBiYOEzQZZ/Rk/gauc9GFvlV3rcYm6C8RIjrLF8dTCLoGXVa1c4jmo5oPf9L47ZjhJozJdG0WFOXBZUMQ3/q6sXMwP8PxjOTs01JHYfgRGUtJ5V8BUKZz5039p+KCIU06eYm8oRnFcpQ468Wf3Opn+yxHizUqI+YEFqizS0k/y2t2Qbon4XhuaxqXedFDaFBNf7bGIcMkrViZk99lLaYGsNZGhhNeu1xreCA2lLy2+FvO1Pc33I9dd40eWUoJT+eoQBrqPL1mLQjU7pVfIjU7pTTHJBBZNQhtsyU1VgKE6yknzbiorNOwZtVIC7n8aeijSwns9tnRR1y14y5vEY8kOl5jL8KeluyWUdoCCOos="
    file_glob: true
    file: .build/release/bitriseTrigger_osx
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = "osx"
